services:
  - type: web
    name: ldss-backend
    env: node
    region: oregon
    plan: free
    rootDir: backend
    buildCommand: npm install && npm run build && npx prisma generate && npx prisma migrate deploy && npx tsx add-users.ts
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: postgresql://ldss_user:PKIdNJSXaREYFeu3Yuls7S1hX6htgBP7@dpg-d5ae6kre5dus73f2em3g-a.oregon-postgres.render.com/ldss_db_xtcq
        sync: false
      - key: JWT_SECRET
        value: super-secret-ldss-key
      - key: PORT
        value: 4000
